export enum Status {
  INITIATED = 'INITIATED',
  PRICED = 'PRICED',
  ASSIGNED = 'ASSIGNED',
  SUBMITTED = 'SUBMITTED',
  INCORRECT = 'INCORRECT',
  APPROVED = 'APPROVED',
  COMPLETED = 'COMPLETED',
}
